### ISSUE TITLE
API connection error without connection problems

### ISSUE THREAD

**Issue by SeerBird** [nidhaloff/deep-translator#75] opened 2021-07-26 07:34 UTC
* deep_translator version:1.5.0
* Python version: 3.9
* Operating System: Windows 10

### Description

I was trying to execute this line: result += GoogleTranslator(source='ru', target='uk').translate(trans), where trans is a proper unicode string

### What I Did

Here's the traceback:
Traceback (most recent call last):
  File "C:\Users\ilyag\Desktop\Translation\Translate.py", line 35, in <module>
    print(translate(data[0]['content']))
  File "C:\Users\ilyag\Desktop\Translation\Translate.py", line 22, in translate
    result += GoogleTranslator(source='ru', target='uk').translate(trans)
  File "C:\Users\ilyag\Desktop\Translation\venvpy\lib\site-packages\deep_translator\google_trans.py", line 100, in translate
    raise RequestError()
deep_translator.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again

**Comment by nothead31** [comment] 2021-07-26 15:26
Are you able to reproduce the error with different text in _trans_? Can  you provide a sample of the text that causes the error along with intended output (what output appears when using the google translator in your browser?)

**Comment by nidhaloff** [comment] 2021-08-01 20:13
@SeerBird I'm closing this since you did not provide a reproducible example

**Closed by nidhaloff** 2021-08-01 20:13 UTC
Labels: bug
